apiVersion: v1
kind: Service
metadata:
  name: db-services
  labels:
    app: db-services
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30778
  selector:
    app: db-services

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-services-sts
spec:
  selector:
    matchLabels:
      app: db-services
  serviceName: "db-services"
  replicas: 1
  template:
    metadata:
      labels:
        app: db-services
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: db-services
        image: mariadb:10.3
        ports:
        - containerPort: 3306
          name: db-services
        volumeMounts:
        - name: moodle-db
          mountPath: /var/lib/mysql
        - name: tz-config
          mountPath: /etc/localtime
        env:
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
      volumes:
      - name: mysql-config
        configMap:
          name: mariadb-config
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/America/Mexico_City
          type: File
  volumeClaimTemplates:
  - metadata:
      name: moodle-db
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 5Gi