apiVersion: v1
kind: Service
metadata:
  name: nginx-app
spec:
  selector:
    app: nginx-app
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 80
    nodePort: 30770
  type: LoadBalancer

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-app-sts
spec:
  selector:
    matchLabels:
      app: nginx-app
  serviceName: "nginx-app"
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-app
        image: ileonelperea/leonel-nginx:1.0.0
        ports:
        - containerPort: 80
          name: nginx-app