apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: app

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-statefulset
spec:
  selector:
    matchLabels:
      app: app
  serviceName: "app"
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: app
        # Specify image of the service
        # image: URL
        ports:
        - containerPort: 80
          name: web
        env:  
        - name: DB_HOST
          value: "db-services"
        - name: DB_USER
          value: "user"
        - name: DB_PASS
          value: "password"
        - name: DB_DB
          value: "test"
        - name: TZ
          value: "America/Mexico_City"